% Create a waveguideCircular antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:07-Aug-2026 16:42:27

%% Antenna Properties 

antennaObject = design(waveguideCircular, 1420*1e6);
antennaObject.Conductor.Name = 'Aluminium';
antennaObject.Conductor.Conductivity = 3.77*1e7;
antennaObject.Conductor.Thickness = 0.000762;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1420*1e6;
% Define frequency range 
freqRange = (1278:14.2:1562)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)

