% Create a waveguideCircular antenna
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:07-Aug-2026 16:48:17

%physics lol

c = 3e8;    %m/s
f = 1.42e9; %Hz, 21 cm line
l = c/f;   %m, wavelength

%based on properties of a size 10 can

d = 0.157; %m, diameter
h = 0.178; %m, height
r = d/2;   %m, radius

%design computations

lc = (2*pi*r)/1.8412;       %m, cutoff wavelength
Lg = 0.343;                 %m, guide wavelength

%% Antenna Properties 

antennaObject = design(waveguideCircular, 1420*1e6);
antennaObject.Radius = r;
antennaObject.Height = h;
antennaObject.FeedHeight = 0.0528;
antennaObject.FeedOffset = 0.0857;

antennaObject.Conductor.Name = 'Aluminium';
antennaObject.Conductor.Conductivity = 3.77*1e7;
antennaObject.Conductor.Thickness = 0.000762;

% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1420*1e6;
% Define frequency range 
freqRange = (1278:14.2:1562)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)


