% Create a dipole antenna backed with reflectorCorner
% Generated by MATLAB(R) 26.1 and Antenna Toolbox 26.1
%Generated on:08-Aug-2026 02:25:44

%% Antenna Properties 

obj = reflectorCorner;
obj.Exciter= dipole;
antennaObject = design(obj, 2200*1e6);
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 1420*1e6;
% Define frequency range 
freqRange = (1278:14.2:1562)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% pattern
figure;
pattern(antennaObject, plotFrequency)% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
figure;
patternAzimuth(antennaObject, plotFrequency, 90, 'Azimuth', 0:5:360)

figure;
patternElevation(antennaObject, plotFrequency, 0, 'Elevation', 0:5:360)
figure;
patternElevation(antennaObject, plotFrequency, 90, 'Elevation', 0:5:360)



